apiVersion: v1
kind: Pod
metadata:
  name: ci-pod
  labels:
    app: ci

spec:
  containers:
    - name: ci-container
      image: nginx:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cisvc
  labels:
    app: ci

spec:
  type: ClusterIP
  selector:
    app: ci
  ports:
    - name: svc-port
      port: 80
      targetPort: 80
