apiVersion: v1
kind: Pod
metadata: 
  name: lb-pod
  labels:
    app: lb-ci
spec:
  containers: 
    - name: apache-container
      image: httpd:latest
      ports:
        - name: apache-port
          containerPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: lb-services
  labels:
    app: lb-ci

spec:
  type: LoadBalancer
  selector:
    app: lb-ci
  ports:
    - name: lb-svc-pod
      port: 80
      targetPort: 80