apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-pod
  labels:
    app: rs

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: rs
    
  template:
    metadata:
      labels:
        app: rs

    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - name: nginx-port
              containerPort: 80