apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mobile-deployment 
  labels: 
    app: mobile 
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels: 
      app: mobile
  template: 
    metadata: 
      labels: 
        app: mobile 
    spec: 
      containers: 
        - name: nginx-container
          image: nginx:latest
          ports: 
            - containerPort: 80
          
          resources: 
            requests: 
              cpu: "100m"
              memory: "64Mi"
            limits: 
              cpu: "200m"
              memory: "128Mi"