apiVersion: v1 
kind: Service 
metadata: 
  name: mobile-svc
  labels: 
    app: mobile
spec: 
  type: ClusterIP
  selector: 
    app: mobile
  ports: 
    - name: mobile-svc-port 
      protocol: TCP 
      port: 80
      targetPort: 80