apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: laptop-deployment 
  labels: 
    app: laptop
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels: 
      app: laptop
  template: 
    metadata: 
      labels: 
        app: laptop
    spec: 
      containers: 
        - name: tomcat-container
          image: tomcat:10.1
          ports: 
            - containerPort: 8080
          
          resources: 
            requests: 
              cpu: "100m"
              memory: "64Mi"
            limits: 
              cpu: "200m"
              memory: "128Mi"